--------------------------------------------------------
-- Archivo creado  - noviembre-2023   
--------------------------------------------------------

PROMPT APP_GEST_PAQU_SCHEMA.sql;

ALTER SESSION SET CURRENT_SCHEMA=APP_GEST_PAQU;
/

PROMPT --------------CREATING TABLES -------------------

PROMPT COMMISSIONS.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\COMMISSIONS.sql
/

PROMPT CONTRACTORS.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\CONTRACTORS.sql
/

PROMPT CONTRACTORS_VEHICLES.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\CONTRACTORS_VEHICLES.sql
/

PROMPT DRIVERS.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\DRIVERS.sql
/

PROMPT LIQUIDATIONS.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\LIQUIDATIONS.sql
/

PROMPT PACKAGES.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\PACKAGES.sql
/

PROMPT TRIPS.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\TRIPS.sql
/

PROMPT VEHICLES.sql
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\VEHICLES_TRIPS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TABLES\ZONES.sql
/

PROMPT --------------CREATING SEQUENCES-----------------

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\SEQUENCES\SEQ_COMMISSIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\SEQUENCES\SEQ_LIQUIDATIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\SEQUENCES\SEQ_PACKAGES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\SEQUENCES\SEQ_TRIP_ID.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\SEQUENCES\SEQ_ZONES.sql
/

PROMPT --------------CREATING INDEXES-------------------

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_ID_COMMISSION.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_NIT.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_NIT_LICENSE_PLATE.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_IDENTIFICATION_CARD.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_ID_LIQUIDATION.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_PACKAGES_ID.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_TRIPS_ID.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_LICENSE_PLATE.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_LICENSE_PLATE_ID_TRIP.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\INDEXES\PK_ZONES_ID.sql
/


PROMPT --------------CREATING REFERENCES-------------------

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\COMMISSIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\CONTRACTORS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\CONTRACTORS_VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\DRIVERS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\LIQUIDATIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\PACKAGES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\TRIPS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\VEHICLES_TRIPS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\CONSTRAINTS\ZONES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\REF_CONSTRAINTS\CONTRACTORS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\REF_CONSTRAINTS\CONTRACTORS_VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\REF_CONSTRAINTS\LIQUIDATIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\REF_CONSTRAINTS\PACKAGES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\REF_CONSTRAINTS\VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\REF_CONSTRAINTS\VEHICLES_TRIPS.sql
/

PROMPT --------------CREATING TRIGGERS-------------------

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TRIGGERS\LIQUIDATIONS_ID.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\TRIGGERS\ZONES_ID.sql
/

PROMPT --------------PL/SQL------------------------

PROMPT
C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\PLSQL\CALCULATE_PAYMENT_AND_INSERT.sql
/

PROMPT --------------INSERT DATA-------------------
PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\COMMISSIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\CONTRACTORS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\CONTRACTORS_VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\DRIVERS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\LIQUIDATIONS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\PACKAGES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\TRIPS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\VEHICLES.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\VEHICLES_TRIPS.sql
/

PROMPT
@C:\Proyecto\TC_GB_28\APP_GEST_PAQU_DB_TC28\DATA_TABLE\ZONES.sql
/

PROMPT --------------ALL OBJECTS SUCCESSFULLY CREATED------------------

PROMPT ----------------------------------------------------------------
PROMPT END OF APP_GEST_PAQU_SCHEMA.sql
PROMPT ----------------------------------------------------------
