--CREAR USUARIO
CREATE USER APP_GEST_PAQU IDENTIFIED BY appgestpaqu;

-- USER SQL
ALTER USER "APP_GEST_PAQU"
DEFAULT TABLESPACE "TS_APP_GEST_PAQU"
TEMPORARY TABLESPACE "TS_APP_GEST_PAQU_TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "APP_GEST_PAQU" QUOTA UNLIMITED ON "TS_APP_GEST_PAQU";
