--------------------------------------------------------
--  Ref Constraints for Table CONTRACTORS_VEHICLES
--------------------------------------------------------

  ALTER TABLE "APP_GEST_PAQU"."CONTRACTORS_VEHICLES" ADD CONSTRAINT "FK_CONTRACTORS_VEHICLES_NIT" FOREIGN KEY ("NIT") REFERENCES "APP_GEST_PAQU"."CONTRACTORS" ("NIT") ENABLE;
  ALTER TABLE "APP_GEST_PAQU"."CONTRACTORS_VEHICLES" ADD CONSTRAINT "FK_CONTRACTORS_VEHICLES_LICENSE_PLATE" FOREIGN KEY ("LICENSE_PLATE") REFERENCES "APP_GEST_PAQU"."VEHICLES" ("LICENSE_PLATE") ENABLE;
