--------------------------------------------------------
--  Ref Constraints for Table VEHICLES_TRIPS
--------------------------------------------------------

  ALTER TABLE "APP_GEST_PAQU"."VEHICLES_TRIPS" ADD CONSTRAINT "FK_VEHICLE_TRIPS_LICENSE_PLATE" FOREIGN KEY ("LICENSE_PLATE") REFERENCES "APP_GEST_PAQU"."VEHICLES" ("LICENSE_PLATE") ENABLE;
  ALTER TABLE "APP_GEST_PAQU"."VEHICLES_TRIPS" ADD CONSTRAINT "FK_VEHICLE_TRIPS_ID_TRIP" FOREIGN KEY ("ID_TRIP") REFERENCES "APP_GEST_PAQU"."TRIPS" ("ID") ENABLE;
