--------------------------------------------------------
--  Ref Constraints for Table VEHICLES
--------------------------------------------------------

  ALTER TABLE "APP_GEST_PAQU"."VEHICLES" ADD CONSTRAINT "FK_ID_ZONE_VEHICLES" FOREIGN KEY ("ID_ZONE") REFERENCES "APP_GEST_PAQU"."ZONES" ("ID") ENABLE;
  ALTER TABLE "APP_GEST_PAQU"."VEHICLES" ADD CONSTRAINT "FK_ID_DRIVER_VEHICLES" FOREIGN KEY ("ID_DRIVER") REFERENCES "APP_GEST_PAQU"."DRIVERS" ("IDENTIFICATION_CARD") ENABLE;
