REM INSERTING into APP_GEST_PAQU.COMMISSIONS
SET DEFINE OFF;
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('66','14781','75555');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('41','1000','8000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('61','4800','5500');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('62','7000','9000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('67','10000','8000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('68','8800','6000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('64','10000','25500');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('65','50000','7500');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('1','2000','3000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('21','3000','2000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('22','5000','8000');
Insert into APP_GEST_PAQU.COMMISSIONS (ID,PER_TRIP_COMMISSION,PER_DELIVERY_COMMISSION) values ('63','15000','7000');
