REM INSERTING into APP_GEST_PAQU.LIQUIDATIONS
SET DEFINE OFF;
Insert into APP_GEST_PAQU.LIQUIDATIONS (ID,TRIPS,DELIVERIES,DATE_LIQUIDATION,ID_COMMISSION,TOTAL_VALUE) values ('5','1','10',to_date('13/11/23','DD/MM/RR'),'21','23000');
Insert into APP_GEST_PAQU.LIQUIDATIONS (ID,TRIPS,DELIVERIES,DATE_LIQUIDATION,ID_COMMISSION,TOTAL_VALUE) values ('1','1','3',to_date('11/11/23','DD/MM/RR'),'41','25000');
Insert into APP_GEST_PAQU.LIQUIDATIONS (ID,TRIPS,DELIVERIES,DATE_LIQUIDATION,ID_COMMISSION,TOTAL_VALUE) values ('2','2','5',to_date('13/11/23','DD/MM/RR'),'1','19000');
Insert into APP_GEST_PAQU.LIQUIDATIONS (ID,TRIPS,DELIVERIES,DATE_LIQUIDATION,ID_COMMISSION,TOTAL_VALUE) values ('3','1','12',to_date('13/11/23','DD/MM/RR'),'65','140000');
Insert into APP_GEST_PAQU.LIQUIDATIONS (ID,TRIPS,DELIVERIES,DATE_LIQUIDATION,ID_COMMISSION,TOTAL_VALUE) values ('4','1','11',to_date('13/11/23','DD/MM/RR'),'64','290500');
Insert into APP_GEST_PAQU.LIQUIDATIONS (ID,TRIPS,DELIVERIES,DATE_LIQUIDATION,ID_COMMISSION,TOTAL_VALUE) values ('6','1','11',to_date('13/11/23','DD/MM/RR'),'68','74800');
