REM INSERTING into APP_GEST_PAQU.PACKAGES
SET DEFINE OFF;
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('21','ropa adulto','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('19','Juguetes','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('20','ropa niño','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('22','Juguetes','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('23','Ropa','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('25','Calzado','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('24','Accesorios','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('26','Calzado','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('28','Accesorios','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('29','Calzado','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('30','Calzado','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('31','Ropa','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('32','Electrónica','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('33','Alimentos','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('34','Joyería','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('35','Muebles','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('36','Juguetes','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('37','Calzado','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('38','Deportes','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('39','Belleza','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('40','Electromésticos','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('41','Libros','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('42','Herramientas','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('43','Jardinería','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('44','Tecnología','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('45','Mascotas','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('46','Automóviles','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('47','Artesanías','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('48','Instrumentos musicales','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('49','Material de oficina','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('50','Ropa deportiva','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('51','Productos para bebés','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('52','Ropa interior','1','5','9');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('53','Equipaje','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('54','Ropa de cama','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('55','Productos de limpieza','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('56','Ropa','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('57','Electrónica','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('58','Alimentos','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('59','Joyería','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('60','Muebles','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('61','Juguetes','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('62','Calzado','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('63','Deportes','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('64','Belleza','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('65','Electromésticos','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('66','Libros','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('67','Herramientas','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('68','Jardinería','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('69','Tecnología','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('70','Mascotas','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('71','Automóviles','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('72','Artesanías','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('73','Instrumentos musicales','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('74','Material de oficina','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('75','Ropa deportiva','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('76','Productos para bebés','0','4','6');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('77','Ropa interior','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('78','Equipaje','1','1','5');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('79','Ropa de cama','0','3','10');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('80','Productos de limpieza','0','2','7');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('81','Elementos de deporte','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('82','Ropa','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('83','Electrónica','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('84','Alimentos','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('85','Joyería','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('86','Muebles','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('87','Juguetes','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('88','Calzado','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('89','Deportes','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('90','Belleza','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('91','Electromésticos','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('92','Libros','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('93','Herramientas','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('94','Jardinería','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('95','Tecnología','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('96','Mascotas','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('97','Automóviles','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('98','Artesanías','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('99','Instrumentos musicales','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('100','Material de oficina','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('101','Ropa deportiva','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('102','Productos para bebés','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('103','Ropa interior','0','5','11');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('104','Equipaje','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('105','Ropa de cama','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('106','Productos de limpieza','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('108','Ropa','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('109','Electrónica','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('110','Alimentos','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('111','Joyería','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('112','Muebles','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('113','Juguetes','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('114','Calzado','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('115','Deportes','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('116','Belleza','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('117','Electromésticos','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('118','Libros','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('119','Herramientas','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('120','Jardinería','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('121','Tecnología','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('122','Mascotas','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('123','Automóviles','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('124','Artesanías','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('125','Instrumentos musicales','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('126','Material de oficina','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('127','Ropa deportiva','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('128','Productos para bebés','0','4','13');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('129','Ropa interior','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('130','Equipaje','1','1','12');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('131','Ropa de cama','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('132','Productos de limpieza','0','2','14');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('107','Elementos de deporte','0','3','15');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('133','comida','0','2','17');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('134','Ropa','0','4','18');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('135','Electrónica','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('136','Alimentos','0','2','17');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('137','Joyería','0','3','19');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('138','Muebles','0','1','20');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('139','Juguetes','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('140','Calzado','0','1','20');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('141','Deportes','0','2','17');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('142','Belleza','0','4','18');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('143','Electromésticos','0','3','19');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('144','Libros','0','3','19');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('145','Herramientas','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('146','Jardinería','0','4','18');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('147','Tecnología','0','1','20');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('148','Mascotas','0','2','17');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('149','Automóviles','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('150','Artesanías','0','4','18');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('151','Instrumentos musicales','0','1','20');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('152','Material de oficina','0','3','19');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('153','Ropa deportiva','0','2','17');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('154','Productos para bebés','0','4','18');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('155','Ropa interior','0','5','16');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('156','Equipaje','0','1','20');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('157','Ropa de cama','0','3','19');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('158','Productos de limpieza','0','2','17');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('3','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('4','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('5','tecnologia','1','2','2');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('1','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('2','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('6','tecnologia','1','2','2');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('7','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('8','tecnologia','1','3','3');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('9','tecnologia','1','3','3');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('10','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('11','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('12','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('13','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('14','tecnologia','1','1','1');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('15','tecnologia','1','1','4');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('16','tecnologia','1','1','4');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('17','tecnologia','1','1','4');
Insert into APP_GEST_PAQU.PACKAGES (ID,CATEGORY,STATUS,ID_ZONE,ID_TRIP) values ('18','comida','1','2','2');
