REM INSERTING into APP_GEST_PAQU.VEHICLES_TRIPS
SET DEFINE OFF;
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('ABC123','4');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('ABC456','2');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('ABC789','3');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('ABC987','1');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('ASD456','7');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('DEF789','9');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('PWA789','5');
Insert into APP_GEST_PAQU.VEHICLES_TRIPS (LICENSE_PLATE,ID_TRIP) values ('WQB441','12');
